# 3D forest height mapping

```{r}
libs <- c(
  "tidyverse", "sf", "geodata","terra", "classInt", "rayshader"
)
```

```{r}
installed_libs <- libs %in% rownames(
  installed.packages()
)
```

```{r}
if(any(installed_libs == F)){
  install.packages(
    libs[!installed_libs])
}
invisible(lapply(
  libs,
  library,
  character.only = T
))
```

```{r}
url <- "https://libdrive.ethz.ch/index.php/s/cO8or7iOe5dT2Rt/download?path=%2F3deg_cogs&files=ETH_GlobalCanopyHeight_10m_2020_N09E003_Map.tif"
```

```{r}
destfile <- "ETH_GlobalCanopyHeight_10m_2020_N09E003_Map.tif"
download.file(url, destfile, mode = "wb")
```
```{r}
setwd("C:/Users/Ezekiel Godwin/Dropbox/PC/Downloads/Projects/Tree_Height")
```

```{r}
current_path <- "C:/Users/Ezekiel Godwin/OneDrive/Documents/ETH_GlobalCanopyHeight_10m_2020_N09E003_Map.tif"
```

```{r}
new_file_path <- "C:/Users/Ezekiel Godwin/Dropbox/PC/Downloads/Projects/Tree_Height/ETH_GlobalCanopyHeight_10m_2020_N09E003_Map.tif"
```

```{r}
if (file.rename(current_path, new_file_path)) {
  message("File moved successfully.")
} else {
  message("File move failed.")
}
```

```{r}
raster_file <- list.files(path = getwd(), pattern = "ETH", full.names = T)
```


```{r}
install.packages("rnaturalearth")
```

```{r}
library(sf)
```

```{r}
shapefile_path <- "C:/Users/Ezekiel Godwin/Dropbox/PC/Downloads/Projects/Tree_Height/nig_for.shp"
forest <- st_read(shapefile_path, options = "ENCODING=UTF-8")
```

```{r}
print(niger)
```
```{r}
plot(st_geometry(forest))
```
```{r}
dim(forest)
```

# LOAD FOREST HEIGHT
#.............................

```{r}
fh_rast <- rast(raster_file)
```

```{r}
forest_bd <- vect(shapefile_path)
```

# AGGREGATE
```{r}
fh_agg <- aggregate(fh_rast, fact = 10, fun = mean)
```
```{r}
fh_forest <- crop(fh_agg, forest_bd, snap = "in")
```

```{r}
forest_masked <- mask(fh_forest, niger_bd)
```

# PLOT THE CLIPPED RASTER
```{r}
plot(forest_masked)
```

#RASTER TO DATAFRAME
#.............

```{r}
forest_masked
```

```{r}
fh_df <- as.data.frame(forest_masked, xy = TRUE)
```

```{r}
head(fh_df, 100)
```

```{r}
head(fh_df)
```

```{r}
colnames(fh_df) <- c("x", "y", "height")
```

```{r}
names(fh_df)[3] <- "height"
```

# SUBSET
```{r}
fh_df_subset <- fh_df[sample(nrow(fh_df), 1000), ]
```

```{r}
fh_df_subset
```

# BREAKS

```{r}
breaks_subset <- classInt::classIntervals(
  fh_df_subset$height,
  n = 5,
  style = "fisher"
)$brks
```


#........................

```{r message=TRUE, warning=TRUE}
breaks <- classInt::classIntervals(
  fh_df$height,
  n = 5,
  style = "fisher"
)$brks
```

```{r}
cols <-
  c(
    "white", "#ffd3af", "#fbe06e",
    "#6daa55", "#205544"
  )
```

```{r}
texture <- colorRampPalette(
  cols,
  bias = 2
)(6)
```

```{r}
p <- ggplot(
  fh_df
) +
 geom_tile(
    aes(
      x = x,
      y = y,
      fill = height
      )
  )+
  scale_fill_gradientn(
    name = "height (m)",
    colors = texture,
    breaks = round(breaks, 0)
)+
coord_sf(crs = 4326)+
  guides(
    fill = guide_legend(
      direction = "vertical",
      keyheight = unit(5, "mm"),
      keywidth = unit(5, "mm"),
      title.position = "top",
      label.position = "right",
      title.hjust = 0.5,
      label.hjust = 0.5,
      ncol = 1,
      byrow = FALSE
    )
) +
theme_minimal() +
theme(
  axis.line = element_blank(),
  axis.title.x = element_blank(), 
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  legend.position ="right",
  legend.title = element_text(size = 11, color = "grey10"),
  legend.text = element_text(size = 11, color = "grey10"),
  panel.grid.major = element_line(color = "white"),
  plot.background = element_rect(fill = "white", color = NA),
  panel.border = element_rect(fill = NA, color = "white"),
  plot.margin = unit(c(t = 0, r = 0, b = 0, l = 0), "lines")
)
```


# RENDER SCENE
#......................

```{r}
h <- nrow(fh_df)
w <- ncol(fh_df)
```


```{r}
max_dimension <- 50  # Maximum dimension in inches

# Calculate the aspect ratio
aspect_ratio <- w / h

# Adjust width and height to fit within the maximum dimension
if (aspect_ratio > 1) {
  width_in_inches <- max_dimension
  height_in_inches <- max_dimension / aspect_ratio
} else {
  height_in_inches <- max_dimension
  width_in_inches <- max_dimension * aspect_ratio
}
```

```{r}
options(ragg.max_dim = 10000)  # Set a higher max dimension (e.g., 100,000 pixels)

rayshader::plot_gg(
  ggobj = p,
  width = 10,
  height = 10,
  scale = 150,
  solid = FALSE,
  soliddepth = 0,
  shadow = TRUE, 
  shadow_intensity =0.99,
  offset_edges = FALSE,
  sunangle = 315,
  #window.size = c(800, 800),
  zoom = 0.4,
  phi = 30,
  theta = -30,
  multicore = TRUE
)


```

```{r}
rayshader::render_camera(
  phi = 50,
  zoom = .7,
  theta = 45
)
```

```{r}
ggplot2::ggsave(
  filename = "niger-forest-height-2020.png",
  plot = last_plot(),  # Assuming the plot is the last one created
  width = 10,  # Adjust width to desired size (in pixels)
  height = 10,  # Adjust height to desired size (in pixels)
  dpi = 300,  # Set the DPI (dots per inch) for resolution
  limitsize = FALSE  # Override size limit
)
```

# RENDER OBJECT
```{r}
rayshader::render_highquality(
  filename = "niger-forest-height-2020.png",
  preview = TRUE,
  interactive = FALSE,
  light = TRUE,
  lightdirection = c(
    315, 310, 315, 310
  ),
  lightintensity = c(
    1000, 1500, 150, 100
  ),
  lightaltitude = c(
    15, 15, 80, 80
  ),
  ground_material =
  rayrender::microfacet(
    roughness = 0.6
  ),
  width = 10,
  height = 10,
)
```

